data: 
  # Batch size either int or null, for example: batch_size: 32 or batch_size: null
  train_batch_size: 8
  test_batch_size: 2
  # The dataset to use options are: mnist, wine, or simple for example: dataset: 'mnist'
  dataset: 'single'

trainer: 
  epochs: 5

model:
  # The input features as int, will also be the output features example: in_out_features: 784 
  in_out_features: 4
  # The hidden sizes of the layers between input and ouput for example: hidden_sizes: [512, 256, 512]
  hidden_sizes: [2]
  # Options are: 'cuda', 'cpu'
  device: 'cuda'

path: 
  csv_save_path: './log'
  csv_name: 'result.csv'
  plot_save_path: './image'
  plot_name: 'autoencoder'